-- Restored Data Import
USE business_php;

INSERT IGNORE INTO User (id, name, email, password) VALUES (1, 'Firaol', 'firaol@example.com', '$2y$12$uoCOLjPlyIJ9NxHcBHNy5.mn7x5Caf8X/12hZWQaF/xjj2m41Qeoi');

INSERT INTO BusinessExpense (userId, category, description, amount, expenseDate, paymentMethod, note) VALUES (1, 'Maintenance', 'Showroom repair', 1200, '2025-12-29 00:00:00', 'Cash', '');
INSERT INTO BusinessExpense (userId, category, description, amount, expenseDate, paymentMethod, note) VALUES (1, 'Rent', '2 months rent', 50000, '2025-12-22 00:00:00', 'Bank Transfer', '');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Tomato container', '', 'wip', '2026-01-01 10:45:25', NULL, 6250, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Dining Table', '', 'wip', '2025-12-27 12:22:20', NULL, 0, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Wooden Bed', 'furniture', 'wip', '2025-12-24 18:55:40', NULL, 0, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Corner cabinet', '', 'wip', '2025-12-19 09:54:31', NULL, 0, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Rekebot', '', 'finished', '2025-12-17 05:11:20', '2025-12-19 19:58:33', 0, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Bed', '', 'sold', '2025-12-08 13:32:09', '2025-12-12 15:05:25', 25000, '', 'unpaid');
SET @lastPid = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductSale (productId, quantity, sellingPrice, clientName, soldAt) VALUES (@lastPid, 1, 25000, '', '2025-12-12 15:05:25');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Coffee Table', '', 'wip', '2025-12-04 21:02:19', NULL, 0, '', 'unpaid');
INSERT INTO Product (userId, name, category, status, startedAt, finishedAt, finalSellingPrice, clientName, paymentStatus) VALUES (1, 'Bee Box', '', 'wip', '2025-12-04 20:40:56', NULL, 15500, '', 'unpaid');
SET @pId = (SELECT id FROM Product WHERE name = 'Tomato container' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Raw wood', 100000, '2026-01-01 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Tomato container' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'labor', 'Ambaye', 2000, '2026-01-01 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leg', 9850, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Back board', 7200, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', '9m leather', 7650, '2025-12-30 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Sponge', 4200, '2025-12-30 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'transport', '', 100, '2025-12-30 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Mastish', 750, '2025-12-30 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Hand', 700, '2025-12-30 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leather', 1700, '2026-01-01 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Safariya', 2250, '2026-01-02 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Dining Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Vayzit', 500, '2026-01-02 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Wooden Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'kola', 550, '2025-12-24 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Wooden Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Wood', 6000, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Corner cabinet' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'MDF', 10500, '2025-12-19 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Corner cabinet' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Slider', 1000, '2025-12-22 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Corner cabinet' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'TVP', 375, '2025-12-24 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Corner cabinet' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'sand paper', 140, '2025-12-24 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Corner cabinet' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Kola', 1550, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Mdf', 2290, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Tinner and paint', 1900, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Epoxy', 1500, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leg', 2200, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leg', 325, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Handy', 720, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Mini leg', 480, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leg', 560, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Rekebot' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Zagol', 80, '2025-12-17 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'MDF 3 x 18mm and 1 x 12mm', 12200, '2025-12-08 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Slider 4', 800, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Kola', 1500, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Ganch', 280, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Leather', 850, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Sponge', 1100, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Lether', 425, '2025-12-10 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Tinner', 800, '2025-12-10 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Sofastin', 325, '2025-12-10 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Key', 160, '2025-12-10 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Paint and plaster', 1300, '2025-12-10 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Gaz', 250, '2025-12-11 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bed' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Handy', 160, '2025-12-12 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Metal', 8000, '2025-12-04 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Metal', 1520, '2025-12-04 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Antirest', 350, '2025-12-05 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Epoxy', 1500, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Paint', 1250, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'MDF', 1300, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Coffee Table' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Stiker', 772, '2025-12-27 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Raw Wood', 28000, '2025-12-04 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'transport', '', 900, '2025-12-04 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', '3 kola', 1290, '2025-12-06 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', '2 shooter nail', 1740, '2025-12-06 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'shibo', 330, '2025-12-09 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Paint', 840, '2025-12-11 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Sander', 550, '2025-12-11 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Sander', 420, '2025-12-12 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Kola', 1500, '2025-12-12 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Shooter nail', 780, '2025-12-12 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Maxefiya', 1440, '2025-12-13 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Paint', 420, '2025-12-13 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Nail', 1350, '2025-12-18 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'shibo', 800, '2025-12-19 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Nail', 640, '2025-12-20 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Shibo', 3200, '2025-12-22 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Nail', 1400, '2025-12-24 00:00:00');
SET @pId = (SELECT id FROM Product WHERE name = 'Bee Box' AND userId = 1 ORDER BY id DESC LIMIT 1);
INSERT INTO ProductCost (productId, costType, description, amount, incurredDate) VALUES (@pId, 'material', 'Nail', 340, '2025-12-27 00:00:00');
